### ISSUE TITLE
Exercise/Purpose 작업

### ISSUE THREAD

**Issue by 0seoYun** [LikeLion-at-DGU/backback_backend#31]
### TODO

- [x] 해당 운동 목적 게시글 리스트
- [x] 해당 운동 종목 게시글 리스트
- [x] 게시글 디테일에 Exercise, Purpose 포함
- [x] post/exercise list 아닌 string으로 반환하도록
