### ISSUE TITLE
Profile Receiver 수정

### ISSUE THREAD

**Issue by jihyunniiii** [LikeLion-at-DGU/backback_backend#62]
### TODO
- [x] Profile Receiver에 닉네임 자동 생성 기능 추가
    - [x] Receiver에 nickname_generator 함수 구현
        - 자동 생성되는 닉네임은 울끈이_(영어 소문자 5개)
        - type은 COMMON으로 설정
- [x] Profile 모델 수정
    - intro에 blank=True 추가
